name: Update submodule vyos-1x
on:
  workflow_dispatch:
  schedule:
  # 06:00 UTC on Monday
    - cron:  '0 6 * * 1'
jobs:
  updatVyOS-1x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rebortg/vyos-documentation
      - name: update submodule
        run: |
          git submodule status
          git submodule update --init --force
          cd docs/_include/vyos-1x
          git checkout current
          git pull
          git submodule status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: Update vyos-1x submodule
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update vyos-1x submodule
          body: |
            Autoupdate vyos-1x submodule
          branch: update-dependencies
