name: Update submodule vyos-1x
on:
  workflow_dispatch:
  schedule:
  # 06:00 UTC on Monday
    - cron:  '0 6 * * 1'
jobs:
  update_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: update submodule
        run: |
          git submodule status
          git submodule update --init --force
          cd docs/_include/vyos-1x
          git checkout current
          git pull
          git submodule status
      - name: update releasenotes
        env:
          PHABRICATOR_API: ${{ secrets.PHABRICATOR_API }}
        if: env.PHABRICATOR_API != null
        run: |
          pip3 install phabricator
          python3 docs/_ext/releasenotes.py -t ${{ secrets.PHABRICATOR_API }} -b current equuleus
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: "Github: update current branch"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Github: update current branch"
          body: |
            Autoupdate vyos-1x submodule
            update releasenotes
          branch: update-dependencies-master
          delete-branch: true


  update_equuleus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: equuleus
      - name: update submodule
        run: |
          git submodule status
          git submodule update --init --force
          cd docs/_include/vyos-1x
          git checkout equuleus
          git pull
          git submodule status
      - name: update releasenotes
        env:
          PHABRICATOR_API: ${{ secrets.PHABRICATOR_API }}
        if: env.PHABRICATOR_API != null
        run: |
          pip3 install phabricator
          python3 docs/_ext/releasenotes.py -t ${{ secrets.PHABRICATOR_API }} -b equuleus
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: "Github: update equuleus branch"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Github: update equuleus branch"
          body: |
            Autoupdate vyos-1x submodule
            update releasenotes
          branch: update-dependencies-equuleus
          delete-branch: true
